#! /bin/bash
#SBATCH --job-name=analysis
#SBATCH --partition=teyssier
#SBATCH --time=04:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
##SBATCH --mem=16GB
#SBATCH --mem-per-cpu=4000

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK 

export XDG_RUNTIME_DIR=""
export PATH="/home/cluster/mkrets/miniconda3/bin:$PATH"
export LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=$HOME/local/lib:$DYLD_LIBRARY_PATH
export PATH=$HOME/bin:$PATH

echo "python run:" $*

srun python -uW ignore $*

exit
